In [1]:
import torch
x = torch.arange(4.0, requires_grad=True)
y = x * x
x, y, x.grad


(tensor([0., 1., 2., 3.], requires_grad=True),
 tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>),
 None)

In [2]:
y.sum().backward()
x, y, x.grad


(tensor([0., 1., 2., 3.], requires_grad=True),
 tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>),
 tensor([0., 2., 4., 6.]))

In [5]:
x.grad.zero_()
x.grad

tensor([0., 0., 0., 0.])

In [7]:
y = 2 * torch.dot(x, x)
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [8]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])